!-----------------------------------------------------------------------
! SUBROUTINE TO ALLOCATE ARRAY SIZES FOR THE SPECIFIED SYSTEM SIZE
!-----------------------------------------------------------------------
      SUBROUTINE ALO
      USE VAR 
      IMPLICIT NONE
!      
      NXYZ=NX*NY*NZ
      PRINT '(" >>NOTE - YOU ARE COMPUTING",I8, " POINTS")',NXYZ
      PRINT '(" >>NOTE - EQUIVALENT CUBE SIZE",F6.1, " POINTS")', NXYZ**(1.0/3.0)  
!      
      ALLOCATE(G2(NX,NY,NZ))
      ALLOCATE(G(3,NX,NY,NZ))
      ALLOCATE(BPQ(NP,NQ,NP,NQ,NX,NY,NZ))
      ALLOCATE(ETAK(NP,NQ,NX,NY,NZ))  
      ALLOCATE(ETA(NP,NQ,NX,NY,NZ))
      ALLOCATE(TPR(NX,NY,NZ))
      ALLOCATE(TPK(NX,NY,NZ))  
      ALLOCATE(PHI(NX,NY,NZ))
      ALLOCATE(GC(NPHIS,15))
      ALLOCATE(GSF_EQ(NPHIS))    
      ALLOCATE(DER(NP,NQ,3,NX,NY,NZ))
      ALLOCATE(E0(NP,NQ,3,3))  
      ALLOCATE(SE0(3,3,NX,NY,NZ))  
      ALLOCATE(S0(NP,NQ,3,3)) 
! CONCENTRATION VARIABLES
      ALLOCATE(CONC(NX,NY,NZ))
      ALLOCATE(ONE(NX,NY,NZ))
      ALLOCATE(TWO(NX,NY,NZ))
      ALLOCATE(THREE(NX,NY,NZ))
      ALLOCATE(GDIFF(NX,NY,NZ))
      ALLOCATE(C0(NX,NY,NZ))
      ALLOCATE(CONCFE(NX,NY,NZ))
      ALLOCATE(ALPDG(NX,NY,NZ))
      ALLOCATE(FBENERGY(NX,NY,NZ))
      ALLOCATE(CONCGE(NX,NY,NZ))
      END SUBROUTINE ALO
!-----------------------------------------------------------------------
! SUBROUTINE TO CALCULATE OUTPUT FILE SIZE
!-----------------------------------------------------------------------
      SUBROUTINE BIG
      USE VAR 
      IMPLICIT NONE
      REAL :: FILESIZE
      REAL :: AUXSIZE
      REAL :: TOTALSIZE
!
      IF (OUTDIM == 2) THEN
        FILESIZE=(NX*NZ*17+20)*OUT1
        AUXSIZE=NX*NZ*17
        TOTALSIZE=FILESIZE*(OUTGE+OUTFE+OUTETAS*NQ*NP)+AUXSIZE*(1+NP*NQ)
      ELSE IF (OUTDIM == 3) THEN
        FILESIZE=(NX*NY*NZ*17+20)*OUT1
        AUXSIZE=NX*NY*NZ*17        
        TOTALSIZE=FILESIZE*(OUTGE+OUTFE+OUTETAS*NQ*NP)+AUXSIZE*(1+NP*NQ)     
      END IF
!
      IF(FILESIZE < 1000) THEN
        PRINT '(" >>NOTE - OUTPUT FILE SIZE = ",I4," BYTES")',FILESIZE
      ELSE IF(FILESIZE >= 1000 .AND. FILESIZE<1000000) THEN
        PRINT '(" >>NOTE - OUTPUT FILE SIZE = ",F7.3," KILOBYTES")',FILESIZE/1000
      ELSE IF(FILESIZE >= 1000000 .AND. FILESIZE<1000000000) THEN
        PRINT '(" >>NOTE - OUTPUT FILE SIZE = ",F7.3," MEGABYTES")',FILESIZE/1000000        
      ELSE IF(FILESIZE>=1000000000) THEN
        PRINT '(" >>NOTE - OUTPUT FILE SIZE = ",F7.3," GIGABYTES")',FILESIZE/1000000000
      END IF
!
      IF(TOTALSIZE < 1000) THEN
        PRINT '(" >>NOTE - TOTAL DATA SIZE  = ",I4," BYTES")',TOTALSIZE
      ELSE IF(TOTALSIZE >= 1000 .AND. TOTALSIZE<1000000) THEN
        PRINT '(" >>NOTE - TOTAL DATA SIZE  = ",F7.3," KILOBYTES")',TOTALSIZE/1000
      ELSE IF(TOTALSIZE >= 1000000 .AND. TOTALSIZE<1000000000) THEN
        PRINT '(" >>NOTE - TOTAL DATA SIZE  = ",F7.3," MEGABYTES")',TOTALSIZE/1000000        
      ELSE IF(TOTALSIZE>=1000000000) THEN
        PRINT '(" >>NOTE - TOTAL DATA SIZE  = ",F7.3," GIGABYTES")',TOTALSIZE/1000000000
      END IF
!      
      END SUBROUTINE BIG      
